In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Import dataset for initial inspection

In [13]:
covid_data = pd.read_csv("../data/raw/WHO-COVID-19-global-data.csv")

## Initial inspection 
- First/last rows
- Shape of dataset  
- Column names and dtypes
- Describe

In [6]:
covid_data.head()

,Date_reported,Country_code,Country,WHO_region,New_cases,Cumulative_cases,New_deaths,Cumulative_deaths
0,2020-01-05,AI,Anguilla,AMRO,NaN,0,NaN,0
1,2020-01-12,AI,Anguilla,AMRO,NaN,0,NaN,0
2,2020-01-19,AI,Anguilla,AMRO,NaN,0,NaN,0
3,2020-01-26,AI,Anguilla,AMRO,NaN,0,NaN,0
4,2020-02-02,AI,Anguilla,AMRO,NaN,0,NaN,0

In [8]:
covid_data.tail()

,Date_reported,Country_code,Country,WHO_region,New_cases,Cumulative_cases,New_deaths,Cumulative_deaths
77515,2026-02-08,XXL,International commercial vessel,OTHER,NaN,29,NaN,0
77516,2026-02-15,XXL,International commercial vessel,OTHER,NaN,29,NaN,0
77517,2026-02-22,XXL,International commercial vessel,OTHER,NaN,29,NaN,0
77518,2026-03-01,XXL,International commercial vessel,OTHER,NaN,29,NaN,0
77519,2026-03-08,XXL,International commercial vessel,OTHER,NaN,29,NaN,0

In [7]:
covid_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77520 entries, 0 to 77519
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date_reported      77520 non-null  object
 1   Country_code       77197 non-null  object
 2   Country            77520 non-null  object
 3   WHO_region         71706 non-null  object
 4   New_cases          51020 non-null  float64
 5   Cumulative_cases   77520 non-null  int64
 6   New_deaths         36608 non-null  float64
 7   Cumulative_deaths  77520 non-null  int64
dtypes: float64(2), int64(2), object(4)
memory usage: 4.7+ MB

In [22]:
covid_data.describe().T

,count,mean,std,min,25%,50%,75%,max
New_cases,51020.0,1.527194e+04,2.369791e+05,-65079.0,8.0,150.0,2017.0,40475477.0
Cumulative_cases,77520.0,2.160477e+06,8.834618e+06,0.0,7612.5,63993.0,696614.0,103436829.0
New_deaths,36608.0,1.942998e+02,1.012255e+03,-3432.0,0.0,5.0,50.0,47687.0
Cumulative_deaths,77520.0,2.243399e+04,8.905065e+04,0.0,46.0,743.0,8530.0,1236353.0

In [26]:
covid_data[covid_data["New_cases"]==covid_data["New_cases"].max()]

,Date_reported,Country_code,Country,WHO_region,New_cases,Cumulative_cases,New_deaths,Cumulative_deaths
11539,2022-12-25,CN,China,WPRO,40475477.0,62445650,5849.0,38995

In [27]:
covid_data[covid_data["New_cases"] == covid_data["New_cases"].min()]

,Date_reported,Country_code,Country,WHO_region,New_cases,Cumulative_cases,New_deaths,Cumulative_deaths
50543,2023-08-20,PH,Philippines,WPRO,-65079.0,4108552,0.0,66646

Negative values in 'New_cases' and 'New_deaths'. On further investigation it appears that this might reflect corrections in historical data which can happen when a country has overestimated the number of cases/deaths.

## Nulls & duplicates

### - Nulls

In [12]:
covid_data.isna().sum()/len(covid_data)*100

Date_reported         0.000000
Country_code          0.416667
Country               0.000000
WHO_region            7.500000
New_cases            34.184727
Cumulative_cases      0.000000
New_deaths           52.776058
Cumulative_deaths     0.000000
dtype: float64

At initial inspection, null values appear mostly in 'New_cases' and 'New_deaths'. 
This could be Structurally Missing Data (MNAR) if nulls represent days with zero 
cases/deaths, or Missing at Random (MAR) if they reflect reporting gaps. 
Further inspection is needed to distinguish between the two.

### - Duplicates

In [21]:
covid_data.duplicated().sum()

np.int64(0)

No duplicated rows have been found