In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Starting Data Inspection

## Load first dataset

In [2]:
covid_df = pd.read_csv("../data/raw/WHO-COVID-19-global-daily-data.csv")
covid_df.head()

,Date_reported,Country_code,Country,WHO_region,New_cases,Cumulative_cases,New_deaths,Cumulative_deaths
0,2020-01-04,AF,Afghanistan,EMR,NaN,0,NaN,0
1,2020-01-04,DZ,Algeria,AFR,NaN,0,NaN,0
2,2020-01-04,AL,Albania,EUR,NaN,0,NaN,0
3,2020-01-04,AI,Anguilla,AMR,NaN,0,NaN,0
4,2020-01-04,AS,American Samoa,WPR,0.0,0,0.0,0

In [3]:
covid_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 538080 entries, 0 to 538079
Data columns (total 8 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Date_reported      538080 non-null  object
 1   Country_code       535838 non-null  object
 2   Country            538080 non-null  object
 3   WHO_region         538080 non-null  object
 4   New_cases          213004 non-null  float64
 5   Cumulative_cases   538080 non-null  int64
 6   New_deaths         155252 non-null  float64
 7   Cumulative_deaths  538080 non-null  int64
dtypes: float64(2), int64(2), object(4)
memory usage: 32.8+ MB

In [8]:
covid_df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Date_reported,538080,2242,2026-02-22,240,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Country_code,535838,239,AF,2242,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Country,538080,240,Afghanistan,2242,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WHO_region,538080,7,EUR,139004,NaN,NaN,NaN,NaN,NaN,NaN,NaN
New_cases,213004.0,NaN,NaN,NaN,3657.893429,48261.398445,-65079.0,3.0,59.0,662.0,6966046.0
Cumulative_cases,538080.0,NaN,NaN,NaN,2153323.828743,8814997.68832,0.0,7558.0,63993.0,694542.5,103436829.0
New_deaths,155252.0,NaN,NaN,NaN,45.811661,241.427799,-3520.0,0.0,2.0,14.0,44047.0
Cumulative_deaths,538080.0,NaN,NaN,NaN,22394.376563,88920.777672,0.0,46.0,743.0,8530.0,1235885.0

In [11]:
covid_df.isnull().sum()/len(covid_df)

Date_reported        0.000000
Country_code         0.004167
Country              0.000000
WHO_region           0.000000
New_cases            0.604141
Cumulative_cases     0.000000
New_deaths           0.711470
Cumulative_deaths    0.000000
dtype: float64

In a initial inspection we can see that some features like 'New_cases' or 'New_deaths' appear to have a lot of null values (~60% and ~71% respectively). Nevertheless, these are possibly Missing Not At Random (MNAR) data, since there probably were no new cases or deaths for that particular date. Further inspection needed to confirm

In [18]:
covid_df.duplicated().sum()

np.int64(0)