In [40]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Starting Data Inspection

## Load first dataset

In [41]:
covid_df = pd.read_csv("../data/raw/WHO-COVID-19-global-daily-data.csv")
covid_df.head()

,Date_reported,Country_code,Country,WHO_region,New_cases,Cumulative_cases,New_deaths,Cumulative_deaths
0,2020-01-04,AF,Afghanistan,EMR,NaN,0,NaN,0
1,2020-01-04,DZ,Algeria,AFR,NaN,0,NaN,0
2,2020-01-04,AL,Albania,EUR,NaN,0,NaN,0
3,2020-01-04,AI,Anguilla,AMR,NaN,0,NaN,0
4,2020-01-04,AS,American Samoa,WPR,0.0,0,0.0,0

In [42]:
covid_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 538080 entries, 0 to 538079
Data columns (total 8 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Date_reported      538080 non-null  object
 1   Country_code       535838 non-null  object
 2   Country            538080 non-null  object
 3   WHO_region         538080 non-null  object
 4   New_cases          213004 non-null  float64
 5   Cumulative_cases   538080 non-null  int64
 6   New_deaths         155252 non-null  float64
 7   Cumulative_deaths  538080 non-null  int64
dtypes: float64(2), int64(2), object(4)
memory usage: 32.8+ MB

In [43]:
covid_df.describe(include="all").T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Date_reported,538080,2242,2026-02-22,240,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Country_code,535838,239,AF,2242,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Country,538080,240,Afghanistan,2242,NaN,NaN,NaN,NaN,NaN,NaN,NaN
WHO_region,538080,7,EUR,139004,NaN,NaN,NaN,NaN,NaN,NaN,NaN
New_cases,213004.0,NaN,NaN,NaN,3657.893429,48261.398445,-65079.0,3.0,59.0,662.0,6966046.0
Cumulative_cases,538080.0,NaN,NaN,NaN,2153323.828743,8814997.68832,0.0,7558.0,63993.0,694542.5,103436829.0
New_deaths,155252.0,NaN,NaN,NaN,45.811661,241.427799,-3520.0,0.0,2.0,14.0,44047.0
Cumulative_deaths,538080.0,NaN,NaN,NaN,22394.376563,88920.777672,0.0,46.0,743.0,8530.0,1235885.0

In [44]:
covid_df.isnull().sum()/len(covid_df)

Date_reported        0.000000
Country_code         0.004167
Country              0.000000
WHO_region           0.000000
New_cases            0.604141
Cumulative_cases     0.000000
New_deaths           0.711470
Cumulative_deaths    0.000000
dtype: float64

In a initial inspection we can see that some features like 'New_cases' or 'New_deaths' appear to have a lot of null values (~60% and ~71% respectively). Nevertheless, these are possibly Missing Not At Random (MNAR) data, since there probably were no new cases or deaths for that particular date. Further inspection needed to confirm

In [45]:
covid_df.duplicated().sum()

np.int64(0)

## Load second dataset

In [46]:
vaccines = pd.read_csv("../data/raw/COV_VAC_UPTAKE_2021_2023.csv")
vaccines.head()

,COUNTRY,COVID_VACCINE_ADM_TOT_A1D,COVID_VACCINE_ADM_TOT_BOOST,COVID_VACCINE_ADM_TOT_CPS,COVID_VACCINE_ADM_TOT_DOSES,COVID_VACCINE_ADM_TOT_DOSES_PER100,COVID_VACCINE_COV_TOT_A1D,COVID_VACCINE_COV_TOT_BOOST,COVID_VACCINE_COV_TOT_CPS,COVID_VACCINE_DATE_INTRO_FIRST,COVID_VACCINE_DATE_REPORT_TOT_LAST,DATE
0,BTN,187866.0,NaN,NaN,187866.0,24.0,24.0,NaN,NaN,2021-03-27,2022-10-30,2021-03-28
1,BTN,480836.0,NaN,NaN,480836.0,62.0,62.0,NaN,NaN,2021-03-27,2022-10-30,2021-04-25
2,BTN,483092.0,NaN,NaN,483092.0,63.0,63.0,NaN,NaN,2021-03-27,2022-10-30,2021-05-30
3,BTN,484797.0,NaN,490.0,485619.0,63.0,63.0,NaN,NaN,2021-03-27,2022-10-30,2021-06-27
4,BTN,530103.0,NaN,470465.0,1000568.0,130.0,69.0,NaN,61.0,2021-03-27,2022-10-30,2021-07-25

In [47]:
vaccines.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7608 entries, 0 to 7607
Data columns (total 12 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   COUNTRY                             7608 non-null   object
 1   COVID_VACCINE_ADM_TOT_A1D           7329 non-null   float64
 2   COVID_VACCINE_ADM_TOT_BOOST         4830 non-null   float64
 3   COVID_VACCINE_ADM_TOT_CPS           7101 non-null   float64
 4   COVID_VACCINE_ADM_TOT_DOSES         7426 non-null   float64
 5   COVID_VACCINE_ADM_TOT_DOSES_PER100  7199 non-null   float64
 6   COVID_VACCINE_COV_TOT_A1D           7112 non-null   float64
 7   COVID_VACCINE_COV_TOT_BOOST         4403 non-null   float64
 8   COVID_VACCINE_COV_TOT_CPS           6803 non-null   float64
 9   COVID_VACCINE_DATE_INTRO_FIRST      6807 non-null   object
 10  COVID_VACCINE_DATE_REPORT_TOT_LAST  7375 non-null   object
 11  DATE                                7608 non-null   object
dtypes: float64(8), object(4)
memory usage: 713.4+ KB

In [48]:
vaccines.describe().T

,count,mean,std,min,25%,50%,75%,max
COVID_VACCINE_ADM_TOT_A1D,7329.0,2.111683e+07,1.049170e+08,11.0,191660.0,1951054.0,7978710.0,1.318027e+09
COVID_VACCINE_ADM_TOT_BOOST,4830.0,1.092436e+07,5.811423e+07,1.0,43079.0,575651.0,4364627.5,8.340601e+08
COVID_VACCINE_ADM_TOT_CPS,7101.0,1.900064e+07,9.849577e+07,2.0,163032.0,1427883.0,6887907.0,1.284480e+09
COVID_VACCINE_ADM_TOT_DOSES,7426.0,4.757045e+07,2.480843e+08,20.0,355430.0,3026728.0,17074861.0,3.516881e+09
COVID_VACCINE_ADM_TOT_DOSES_PER100,7199.0,1.179469e+02,8.402130e+01,1.0,44.0,110.0,182.0,4.700000e+02
COVID_VACCINE_COV_TOT_A1D,7112.0,5.224297e+01,2.841871e+01,1.0,28.0,57.0,77.0,1.000000e+02
COVID_VACCINE_COV_TOT_BOOST,4403.0,3.009970e+01,2.295098e+01,1.0,8.0,28.0,51.0,8.300000e+01
COVID_VACCINE_COV_TOT_CPS,6803.0,4.845024e+01,2.771003e+01,1.0,25.0,51.0,72.0,1.000000e+02

In [49]:
vaccines.isnull().sum()/len(vaccines)

COUNTRY                               0.000000
COVID_VACCINE_ADM_TOT_A1D             0.036672
COVID_VACCINE_ADM_TOT_BOOST           0.365142
COVID_VACCINE_ADM_TOT_CPS             0.066640
COVID_VACCINE_ADM_TOT_DOSES           0.023922
COVID_VACCINE_ADM_TOT_DOSES_PER100    0.053759
COVID_VACCINE_COV_TOT_A1D             0.065195
COVID_VACCINE_COV_TOT_BOOST           0.421267
COVID_VACCINE_COV_TOT_CPS             0.105810
COVID_VACCINE_DATE_INTRO_FIRST        0.105284
COVID_VACCINE_DATE_REPORT_TOT_LAST    0.030626
DATE                                  0.000000
dtype: float64

In [50]:
covid_df.shape

(538080, 8)

In [51]:
first_entry = covid_df["Date_reported"].min()
last_entry = covid_df["Date_reported"].max()
print(f"The first data entry in this dataset is from: {first_entry} and the last one from: {last_entry}")

The first data entry in this dataset is from: 2020-01-04 and the last one from: 2026-02-22

In [19]:
vaccines.shape

(7608, 12)

In [52]:
first_entry_vacc = vaccines["DATE"].min()
last_entry_vacc = vaccines["DATE"].max()
print(f"The first data entry in this dataset is from: {first_entry_vacc} and the last one from: {last_entry_vacc}")

The first data entry in this dataset is from: 2021-01-31 and the last one from: 2023-12-31

In [60]:
first_date = covid_df["Date_reported"] >= '2021-01-31'
second_date = covid_df["Date_reported"] <= '2023-12-31'

In [65]:
new_covid = covid_df[second_date & first_date]
new_covid.head()

,Date_reported,Country_code,Country,WHO_region,New_cases,Cumulative_cases,New_deaths,Cumulative_deaths
94320,2021-01-31,ZW,Zimbabwe,AFR,319.0,33271,15.0,1193
94321,2021-01-31,US,United States of America,AMR,164238.0,25863033,3266.0,452123
94322,2021-01-31,ZM,Zambia,AFR,1728.0,53352,17.0,745
94323,2021-01-31,VI,United States Virgin Islands,AMR,NaN,2398,NaN,24
94324,2021-01-31,YE,Yemen,EMR,NaN,2124,NaN,616

In [66]:
new_covid.shape

(255600, 8)

In [67]:
new_first = new_covid["Date_reported"].min()
new_last = new_covid["Date_reported"].max()
print(f"The first data entry in this dataset is from: {new_first} and the last one from: {new_last}")

The first data entry in this dataset is from: 2021-01-31 and the last one from: 2023-12-31